name: Push Image

on:
  release:
    types:
      - published

jobs:
  push_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin

      - name: Build Image
        run: ./gradlew --no-daemon dockerBuildNative

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: |
          SHORT_IMAGE_NAME="$(cut -d/ -f2- <<< ${{ github.repository }}):latest"
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAGGED_IMAGE_NAME="${IMAGE_NAME}:$(sed 's/^v//' <<< ${{ github.ref_name }})"
          LATEST_IMAGE_NAME="${IMAGE_NAME}:latest"
          for image in "$TAGGED_IMAGE_NAME" "$LATEST_IMAGE_NAME"; do
            docker tag "$SHORT_IMAGE_NAME" "$image"
            docker push "$image"
          done
